namespace SMBLibrary.Services
{
    public enum ServerServiceOpName : ushort
    {
        NetrConnectionEnum = 8,
        NetrFileEnum = 9,
        NetrFileGetInfo = 10,
        NetrFileClose = 11,
        NetrSessionEnum = 12,
        NetrSessionDel = 13,
        NetrShareAdd = 14,
        NetrShareEnum = 15,
        NetrShareGetInfo = 16,
        NetrShareSetInfo = 17,
        NetrShareDel = 18,
        NetrShareDelSticky = 19,
        NetrShareCheck = 20,
        NetrServerGetInfo = 21,
        NetrServerSetInfo = 22,
        NetrServerDiskEnum = 23,
        NetrServerStatisticsGet = 24,
        NetrServerTransportAdd = 25,
        NetrServerTransportEnum = 26,
        NetrServerTransportDel = 27,
        NetrRemoteTOD = 28,
        NetprPathType = 30,
        NetprPathCanonicalize = 31,
        NetprPathCompare = 32,
        NetprNameValidate = 33,
        NetprNameCanonicalize = 34,
        NetprNameCompare = 35,
        NetrShareEnumSticky = 36,
        NetrShareDelStart = 37,
        NetrShareDelCommit = 38,
        NetrpGetFileSecurity = 39,
        NetrpSetFileSecurity = 40,
        NetrServerTransportAddEx = 41,
        NetrDfsGetVersion = 43,
        NetrDfsCreateLocalPartition = 44,
        NetrDfsDeleteLocalPartition = 45,
        NetrDfsSetLocalVolumeState = 46,
        NetrDfsCreateExitPoint = 48,
        NetrDfsDeleteExitPoin = 49,
        NetrDfsModifyPrefix = 50,
        NetrDfsFixLocalVolume = 51,
        NetrDfsManagerReportSiteInfo = 52,
        NetrServerTransportDelEx = 53,
        NetrServerAliasAdd = 54,
        NetrServerAliasEnum = 55,
        NetrServerAliasDel = 56,
        NetrShareDelEx = 57,
    }
}